## Assignment 1 - Simple Neural Network
#### Meir Shamir 326198595

### Imports

In [ ]:
import numpy as np

### Defining Sigmoid Function and its Derivative

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    # here x is already sigmoid(x)
    return x * (1 - x)

### Generating Random Weights

In [ ]:
weights = np.random.normal(loc=0.0, scale=1/3, size=(3, 1))
print(weights)

[[ 0.24734805]
 [-0.06394518]
 [-0.29587632]]


### Defining Input And Output Datasets

In [ ]:
X = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
])

y = np.array([
    [0],
    [0],
    [1],
    [1]
])

### Training the Neural Network

In [ ]:
for i in range(1000):

    # Forward pass
    input_layer = X
    outputs = sigmoid(np.dot(input_layer, weights))

    # Error
    error = y - outputs

    # Backpropagation step (gradient descent)
    adjustments = np.dot(input_layer.T, error * sigmoid_derivative(outputs))

    # Update weights
    weights += adjustments

### Printing Results

In [ ]:
print("Final outputs after training:")
print(outputs)

print("\nLearned weights:")
print(weights)

Final outputs after training:
[[0.03187657]
 [0.02571576]
 [0.97912675]
 [0.97409523]]

Learned weights:
[[ 7.26276129]
 [-0.22110146]
 [-3.41403595]]
